### ISSUE TITLE
[Suggestion] - Shorten class name to ar?

### ISSUE THREAD

**Issue by lamualfa** [webdna/tailwindcss-aspect-ratio#14]
We know that **Tailwind CSS** uses abbreviations for some of its class names, like `w` for `width`, `pb` for `padding-bottom`, `mt` for `margin-top`, etc. Don't you intend to use the abbreviation `ar` for `aspect-ratio`?

Example:

- `ar-19/6`
- `ar-2/1`
- `ar-4/3`

more concise than:

- `aspect-ratio-19/6`
- `aspect-ratio-2/1`
- `aspect-ratio-4/3`

That's all. Thank for this awesome plugins.

**Comment by benface** [comment]
I don't feel like aspect ratio is used often enough to justify this (which would be a breaking change, by the way). In Tailwind, many class names are not abbreviations, like [the `pointer-events` utilities](https://tailwindcss.com/docs/pointer-events), or [the top / right / bottom / left ones](https://tailwindcss.com/docs/top-right-bottom-left). I think abbreviations are mostly used for classes that are used very commonly and/or have so many values that it actually makes a difference in the CSS file size. It's not the case here.

**Comment by lamualfa** [comment]
> I don't feel like aspect ratio is used often enough to justify this (which would be a breaking change, by the way). In Tailwind, many class names are not abbreviations, like [the `pointer-events` utilities](https://tailwindcss.com/docs/pointer-events), or [the top / right / bottom / left ones](https://tailwindcss.com/docs/top-right-bottom-left). I think abbreviations are mostly used for classes that are used very commonly and/or have so many values that it actually makes a difference in the CSS file size. It's not the case here.

You are right, that is a reasonable reason. Thank's.
