### ISSUE TITLE
Why the first way in the example in README.md doesn't work?

### ISSUE THREAD

**Issue by lamualfa** [webdna/tailwindcss-aspect-ratio#15]
### Code:

```html
<div class="w-1/2">
  <div class="aspect-ratio-square"></div>
  <img src="thumbnail.jpg" class="absolute left-0 top-0 w-full h-full object-cover">
</div>
```
### Screenshot:
![image](https://user-images.githubusercontent.com/39755201/88739290-6afb2480-d164-11ea-9ee0-85a1d341d388.png)

#### Code:

```html
<div class="relative w-1/2">
  <div class="aspect-ratio-square"></div>
  <img src="thumbnail.jpg" class="absolute left-0 top-0 w-full h-full object-cover">
</div>
```

#### Screenshot:

![image](https://user-images.githubusercontent.com/39755201/88739656-4489b900-d165-11ea-982e-b06482a2f42e.png)

#### and also work with simpler code below:

```html
<div class="relative w-1/2 aspect-ratio-square">
  <img src="thumbnail.jpg" class="absolute left-0 top-0 w-full h-full object-cover">
</div>
```

**Comment by benface** [comment]
Thank you! Fixed in https://github.com/webdna/tailwindcss-aspect-ratio/commit/02308b35e086f95336751b7497f7adbac8f68dad.
