### ISSUE TITLE
css feature

### ISSUE THREAD

**Issue by marlin-2k** [webdna/tailwindcss-aspect-ratio#27]
https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio

Why padding?

**Comment by benface** [comment]
This plugin was created before the `aspect-ratio` property was supported by any browser. You should now use the official [`@tailwindcss/aspect-ratio`](https://github.com/tailwindlabs/tailwindcss-aspect-ratio) plugin. I will add a note to the README. Thank you!
